package main.exception;

public class AssemblerException extends Exception {
	
	/**
	 * serialVersionUID
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 4085135213165385025L;


	/**
	 * Exception error code
	 */
	private int errorCode = -1;
	
	
	/**
	 * Exception error code when bad parameters are given
	 */
	public static final int ERR_LAUNCHER_BAD_PARAMS = 1;
	
	
	/**
	 * Exception error code if an error occurs when the program is being launched
	 */
	public static final int ERR_LAUNCHER_ASM_PROGRAM_FAILED = 2;
	
	
	/**
	 * Exception error code if an error occurs when the program is running
	 */
	public static final int ERR_ASM_RUNTIME_FAILED = 3;
	
	

	/**
	 * Constructor without errorCode
	 * 
	 * @param message
	 */
	public AssemblerException(String message) {
		this(message, 0);
	}
	
	
	
	/**
	 * Constructor with error Code
	 * 
	 * @param message
	 * @param errorCode
	 */
	public AssemblerException(String message, int errorCode) {
		super(message);
		
		if (errorCode >= 0) {
			this.errorCode = errorCode;
		}
	}
	
	
	
	/**
	 * Get the error code
	 * @return errorCode The error code
	 */
	public int getErrorCode() {
		return this.errorCode;
	}
}
